language: generic

sudo: required
services:
    - docker


before_install:
    - docker build -t Mark-Ortner-NRW/docker-react -f Dockerfile.dev . 

script:
    - docker run -e CI=true Mark-Ortner-NRW/docker-react npm run test -- --coverage
