language: generic

sudo: required
services:
    - docker

before_install:
    - docker build -t test-image -f Dockerfile.dev . 

script:
    - docker run -e CI=true test-image npm run test -- --coverage

deploy:
    provider: elasticbeanstalk
    region: "eu-central-1"
    app: "docker"
    env: "Docker-env"     
    bucket_name: "elasticbeanstalk-eu-central-1-696779925067"
    bucket_path: "docker"
    on:
        branch: master

    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
