# language: generic
# sudo: required

#  #services:
#     - docker
# # Test
# before_install:
#     - docker build -t innoq-app -f Dockerfile.dev . 

# script:
#     - docker run -e CI=true innoq-app npm run test -- --coverage

deploy:
    provider: elasticbeanstalk
    region: "eu-central-1"
    app: "innoq-app"
    env: "InnoqApp-env-1"     
    bucket_name: "elasticbeanstalk-eu-central-1-696779925067"
    bucket_path: "innoq-app"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY

after_deploy:
    - echo "Applcation Deployed!"
